name: stock_options_tools
description: Stock Options Visualizer with Yahoo Finance API
version: 1.0.0
repository: https://github.com/nullficks/stock-options-tools

environment:
  sdk: ^3.4.4

dependencies:
  web: ^1.0.0
  http: ^1.2.2
  memory_cache: ^1.2.0
  collection: ^1.19.1

dev_dependencies:
  build_runner: ^2.4.8
  build_web_compilers: ^4.0.9
  lints: ^5.1.1
